import { db, closeDbConnection } from "./index";
import { listings } from "../models/listing.model";
import { users } from "../models/user.model";
import { logger } from "../config/logger";
import { eq } from "drizzle-orm";

export const seedListings = [
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Executive 4-Bed House in East Legon",
    street: "12 Garden Street",
    city: "Accra",
    state: "Greater Accra",
    zipCode: "GE-123-4567",
    county: "Ayawaso West",
    propertyCategory: "Residential",
    propertyType: "Single Family",
    price: "4500000.00",
    pricePerSquareFoot: "1125.00",
    bedrooms: 4,
    bathrooms: "4.5",
    squareFeet: 4000,
    lotSize: "8700.00",
    yearBuilt: 2018,
    stories: 2,
    garageSpaces: 2,
    parkingSpaces: 4,
    condition: "Excellent, like-new condition with modern finishes and POP ceilings.",
    hoaFees: "300.00",
    propertyTaxes: "5000.00",
    annualInsurance: "3500.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: null,
    daysOnMarket: 30,
    listDate: "2025-10-01",
    features: [
      { name: "Swimming Pool" },
      { name: "Boys Quarters" },
      { name: "Electric Fence" },
      { name: "Borehole" },
    ],
    description: "Stunning 4-bedroom executive house in the heart of East Legon. All rooms are ensuite, with a fully fitted kitchen, swimming pool, and standby generator.",
    comparableNotes: "Similar properties on Adjiringanor road sold recently in the $4.3M - $4.6M range.",
    status: "PUBLISHED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Modern 2-Bed Apartment in Cantonments",
    street: "55 Liberation Road",
    city: "Accra",
    state: "Greater Accra",
    zipCode: "GL-088-9012",
    county: "La Dade-Kotopon",
    propertyCategory: "Residential",
    propertyType: "Apartment",
    price: "2800000.00",
    pricePerSquareFoot: "2000.00",
    bedrooms: 2,
    bathrooms: "2.0",
    squareFeet: 1400,
    lotSize: null,
    yearBuilt: 2022,
    stories: 1,
    garageSpaces: 1,
    parkingSpaces: 1,
    condition: "Brand new construction. Pristine condition with high-end fixtures.",
    hoaFees: "1500.00",
    propertyTaxes: "3200.00",
    annualInsurance: "2000.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: null,
    daysOnMarket: 15,
    listDate: "2025-10-15",
    features: [
      { name: "Gym Access" },
      { name: "Rooftop Pool" },
      { name: "24/7 Security" },
      { name: "Backup Generator" },
    ],
    description: "Luxury 2-bedroom apartment in a prestigious complex in Cantonments. Features a communal gym, rooftop pool, and underground parking. Close to embassies and top schools.",
    comparableNotes: "High demand for rental in this area.",
    status: "PUBLISHED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Spacious 5-Bed House in Ahodwo, Kumasi",
    street: "8 Prempeh II Avenue",
    city: "Kumasi",
    state: "Ashanti",
    zipCode: "AK-112-3344",
    county: "Kumasi Metropolitan",
    propertyCategory: "Residential",
    propertyType: "Single Family",
    price: "3200000.00",
    pricePerSquareFoot: "640.00",
    bedrooms: 5,
    bathrooms: "5.0",
    squareFeet: 5000,
    lotSize: "10000.00",
    yearBuilt: 2010,
    stories: 2,
    garageSpaces: 3,
    parkingSpaces: 3,
    condition: "Very good condition. Well-maintained property with mature garden.",
    hoaFees: "0.00",
    propertyTaxes: "4000.00",
    annualInsurance: "2800.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: null,
    daysOnMarket: 60,
    listDate: "2025-09-01",
    features: [
      { name: "Walled and Gated" },
      { name: "Mature Garden" },
      { name: "Poly Tank" },
      { name: "Tiled Compound" },
    ],
    description: "Large family home in the desirable Ahodwo neighborhood. All rooms ensuite, multiple living areas, and a large tiled compound perfect for events. Secure and serene environment.",
    comparableNotes: "Valuation based on recent sales in Ahodwo and Nhyiaeso.",
    status: "PUBLISHED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Commercial Property on Beach Road",
    street: "21 Beach Road",
    city: "Takoradi",
    state: "Western",
    zipCode: "WS-401-7788",
    county: "Sekondi-Takoradi",
    propertyCategory: "Commercial",
    propertyType: "Office Space",
    price: "5000000.00",
    pricePerSquareFoot: "1250.00",
    bedrooms: 0,
    bathrooms: "4.0",
    squareFeet: 4000,
    lotSize: "6000.00",
    yearBuilt: 2005,
    stories: 3,
    garageSpaces: 0,
    parkingSpaces: 15,
    condition: "Good structural condition. Interior needs modernization for new tenant.",
    hoaFees: "0.00",
    propertyTaxes: "8000.00",
    annualInsurance: "5500.00",
    valuationMethod: "INCOME_APPROACH",
    saleDate: null,
    daysOnMarket: null,
    listDate: null,
    features: [
      { name: "High Traffic Area" },
      { name: "Ocean View" },
      { name: "Ample Parking" },
      { name: "Good Visibility" },
    ],
    description: "Prime 3-story commercial building on the busy Beach Road in Takoradi. Ideal for a bank, corporate office, or retail. High visibility and ample parking space.",
    comparableNotes: "Currently in DRAFT. Compiling potential lease income for valuation.",
    status: "DRAFT",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Historic Home in Elmina",
    street: "14 Bantuma Road",
    city: "Elmina",
    state: "Central",
    zipCode: "CK-050-1212",
    county: "KEEA",
    propertyCategory: "Residential",
    propertyType: "Single Family",
    price: "1800000.00",
    pricePerSquareFoot: "514.29",
    bedrooms: 6,
    bathrooms: "4.0",
    squareFeet: 3500,
    lotSize: "7500.00",
    yearBuilt: 1965,
    stories: 2,
    garageSpaces: 1,
    parkingSpaces: 2,
    condition: "Fair condition. Needs significant renovation but has strong bones.",
    hoaFees: "0.00",
    propertyTaxes: "2200.00",
    annualInsurance: "1500.00",
    valuationMethod: "COST_APPROACH",
    saleDate: "2024-05-10",
    daysOnMarket: 120,
    listDate: "2024-01-11",
    features: [
      { name: "Partial Sea View" },
      { name: "Historic Area" },
      { name: "Large Compound" },
    ],
    description: "Large colonial-style property in the historic town of Elmina. Close to the castle and fishing harbor. Great potential for a guesthouse. Sold in May 2024.",
    comparableNotes: "Sold as-is. Price reflects the need for extensive repairs.",
    status: "ARCHIVED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "3-Bed Townhouse in Adentan",
    street: "222 Nii Ashale Street",
    city: "Accra",
    state: "Greater Accra",
    zipCode: "GD-075-1111",
    county: "Adentan Municipal",
    propertyCategory: "Residential",
    propertyType: "Townhouse",
    price: "1200000.00",
    pricePerSquareFoot: "600.00",
    bedrooms: 3,
    bathrooms: "2.5",
    squareFeet: 2000,
    lotSize: "3000.00",
    yearBuilt: 2021,
    stories: 2,
    garageSpaces: 1,
    parkingSpaces: 1,
    condition: "Excellent, recently built. Gated community.",
    hoaFees: "450.00",
    propertyTaxes: "1800.00",
    annualInsurance: "1200.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: null,
    daysOnMarket: 45,
    listDate: "2025-09-16",
    features: [
      { name: "Gated Community" },
      { name: "Community Pool" },
      { name: "24/7 Security" },
    ],
    description: "Modern 3-bedroom townhouse in a secure gated community in Adentan. Finished to a high standard. Includes a fitted kitchen and access to communal amenities.",
    comparableNotes: null,
    status: "PUBLISHED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Half-Acre Plot in Sagnerigu",
    street: "10 Bolga Road",
    city: "Tamale",
    state: "Northern",
    zipCode: "NS-210-9876",
    county: "Sagnerigu",
    propertyCategory: "Land",
    propertyType: "Residential Lot",
    price: "150000.00",
    pricePerSquareFoot: null,
    bedrooms: 0,
    bathrooms: "0.0",
    squareFeet: 1, // Placeholder for land
    lotSize: "21780.00",
    yearBuilt: null,
    stories: null,
    garageSpaces: 0,
    parkingSpaces: 0,
    condition: "Raw land, demarcated and registered. Ready for development.",
    hoaFees: "0.00",
    propertyTaxes: "300.00",
    annualInsurance: "50.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: null,
    daysOnMarket: 10,
    listDate: "2025-10-20",
    features: [
      { name: "Registered Title" },
      { name: "Developing Area" },
      { name: "Utilities Nearby" },
    ],
    description: "Well-located half-acre plot of land in Sagnerigu, a fast-developing area of Tamale. Perfect for building a dream home or for investment. Registered with Lands Commission.",
    comparableNotes: "Priced for a quick sale. Land values in the area are rising.",
    status: "PUBLISHED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "4-Unit Apartment Block in Osu",
    street: "7 Oxford Street",
    city: "Accra",
    state: "Greater Accra",
    zipCode: "GA-055-1234",
    county: "Korle Klottey",
    propertyCategory: "Residential",
    propertyType: "Multi-Family",
    price: "6500000.00",
    pricePerSquareFoot: "1083.33",
    bedrooms: 8,
    bathrooms: "8.0",
    squareFeet: 6000,
    lotSize: "6500.00",
    yearBuilt: 2015,
    stories: 4,
    garageSpaces: 0,
    parkingSpaces: 8,
    condition: "Good condition. Fully tenanted. Regular maintenance.",
    hoaFees: "0.00",
    propertyTaxes: "9000.00",
    annualInsurance: "6000.00",
    valuationMethod: "INCOME_APPROACH",
    saleDate: null,
    daysOnMarket: null,
    listDate: null,
    features: [
      { name: "Fully Tenanted" },
      { name: "Prime Location" },
      { name: "Separate Meters" },
      { name: "High Rental Yield" },
    ],
    description: "Income-producing property! 4-unit apartment block (each 2-bed) in a prime Osu location, just off Oxford Street. Always in high demand. Strong rental yield.",
    comparableNotes: "Owner is retiring. Financials available upon request. (Draft)",
    status: "DRAFT",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Family Home near UPSA",
    street: "30 School Lane",
    city: "Accra",
    state: "Greater Accra",
    zipCode: "GE-200-5000",
    county: "Ga East",
    propertyCategory: "Residential",
    propertyType: "Single Family",
    price: "1900000.00",
    pricePerSquareFoot: "678.57",
    bedrooms: 4,
    bathrooms: "3.5",
    squareFeet: 2800,
    lotSize: "7000.00",
    yearBuilt: 2012,
    stories: 2,
    garageSpaces: 2,
    parkingSpaces: 2,
    condition: "Well-maintained property, perfect for a family. Tiled compound.",
    hoaFees: "0.00",
    propertyTaxes: "2500.00",
    annualInsurance: "1800.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: null,
    daysOnMarket: 50,
    listDate: "2025-09-11",
    features: [
      { name: "Walled and Gated" },
      { name: "Boys Quarters" },
      { name: "Proximity to Schools" },
      { name: "Air Conditioning" },
    ],
    description: "Lovely 4-bedroom home in a quiet neighborhood near UPSA and Legon. Features a 1-bedroom boys quarters, a spacious compound, and easy access to main roads.",
    comparableNotes: "Comps based on recent sales in Legon Hills and Madina.",
    status: "PUBLISHED",
  },
  {
    userId: "567c2692-29ee-4ba8-a5a4-31fc104b2a58",
    title: "Archived: Bungalow at Pedu, Cape Coast",
    street: "44 Coronation Road",
    city: "Cape Coast",
    state: "Central",
    zipCode: "CC-030-4321",
    county: "Cape Coast Metropolitan",
    propertyCategory: "Residential",
    propertyType: "Bungalow",
    price: "950000.00",
    pricePerSquareFoot: "431.82",
    bedrooms: 3,
    bathrooms: "2.0",
    squareFeet: 2200,
    lotSize: "8000.00",
    yearBuilt: 1998,
    stories: 1,
    garageSpaces: 1,
    parkingSpaces: 2,
    condition: "Good condition, but dated interior. Sold to a family.",
    hoaFees: "0.00",
    propertyTaxes: "1200.00",
    annualInsurance: "900.00",
    valuationMethod: "SALES_COMPARISON",
    saleDate: "2024-02-20",
    daysOnMarket: 75,
    listDate: "2023-12-07",
    features: [
      { name: "Large Plot" },
      { name: "Quiet Neighborhood" },
      { name: "Single Story" },
    ],
    description: "Charming 3-bedroom bungalow on a large plot in the Pedu area of Cape Coast. This single-story home was perfect for a family looking for a quiet, established neighborhood.",
    comparableNotes: "Property was sold in February 2024 after 75 days on the market.",
    status: "ARCHIVED",
  },
];

/**
 * Seed the database with listings data
 */
async function seedDatabase() {
  try {
    logger.info("Starting database seeding...");

    // Check if the seed user exists, create if not
    const seedUserId = "567c2692-29ee-4ba8-a5a4-31fc104b2a58";
    const existingUser = await db.query.users.findFirst({
      where: eq(users.id, seedUserId),
    });

    if (!existingUser) {
      logger.info("Seed user not found. Creating test user...");
      await db.insert(users).values({
        id: seedUserId,
        firebaseUid: "seed-test-firebase-uid",
        email: "seed-user@kompa.test",
        name: "Test Seed User",
      });
      logger.info("✅ Test user created");
    } else {
      logger.info("Seed user already exists, skipping user creation");
    }

    // Insert listings
    logger.info(`Inserting ${seedListings.length} listings...`);
    await db.insert(listings).values(seedListings);

    logger.info("Database seeding completed successfully!");
    logger.info(`✅ Inserted ${seedListings.length} listings`);
  } catch (error) {
    logger.error("Error seeding database:", { error });
    throw error;
  } finally {
    await closeDbConnection();
  }
}

// Run the seed function if this file is executed directly
// if (import.meta.url === `file://${process.argv[1]}`) {
//   seedDatabase()
//     .then(() => {
//       process.exit(0);
//     })
//     .catch((error) => {
//       console.error("Seed failed:", error);
//       process.exit(1);
//     });
// }


( async() => {
  return await seedDatabase()
})() 
