export const PUBLIC_LISTING_FIELDS = [
  "id",
  "title",
  "description",
  "city",
  "state",
  "price",
  "bedrooms",
  "bathrooms",
  "squareFeet",
  "propertyType",
  "propertyCategory",
  "yearBuilt",
  "condition",
  "features",
  "userId",
  "createdAt",
] as const;

export const LOCKED_LISTING_FIELDS = [
  "fullAddress",
  "street",
  "zipCode",
  "latitude",
  "longitude",
  "pricePerSquareFoot",
  "comparablePrice",
  "comparableNotes",
  "hoaFees",
  "propertyTaxes",
  "annualInsurance",
  "saleDate",
  "salePrice",
  "daysOnMarket",
  "lotSize",
  "stories",
  "garageSpaces",
  "parkingSpaces",
  "listDate",
] as const;
